# Data Configuration
data_path: "artifacts/train.csv"
preprocessing_path: "models/preprocessing"

# MLflow Configuration
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "houseprice_prediction"
  artifact_path: "model"

# Model Parameters
model_params:
  decision_tree:
    max_depth: 10
    min_samples_split: 2
    random_state: 42

  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42

  xgboost:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42
    objective: 'reg:squarederror'

# Preprocessing Configuration
categorical_features:
  - "MSSubClass"
  - "LotShape"
  - "LandContour"
  - "Utilities"
  - "LandSlope"
  - "OverallQual"
  - "OverallCond"
  - "ExterQual"
  - "ExterCond"
  - "BsmtQual"
  - "BsmtCond"
  - "BsmtExposure"
  - "BsmtFinType1"
  - "BsmtFinType2"
  - "HeatingQC"
  - "CentralAir"
  - "KitchenQual"
  - "FireplaceQu"
  - "GarageFinish"
  - "GarageQual"
  - "GarageCond"
  - "PavedDrive"
  - "PoolQC"
  - "Fence"
  - "Functional"
  - "MSZoning"
  - "Street"
  - "Alley"
  - "LotConfig"
  - "Neighborhood"
  - "Condition1"
  - "Condition2"
  - "BldgType"
  - "HouseStyle"
  - "RoofStyle"
  - "RoofMatl"
  - "Exterior1st"
  - "Exterior2nd"
  - "MasVnrType"
  - "Foundation"
  - "Heating"
  - "Electrical"
  - "GarageType"
  - "MiscFeature"
  - "SaleType"
  - "SaleCondition"

numeric_features:
  - "LotFrontage"
  - "LotArea"
  - "YearBuilt"
  - "YearRemodAdd"
  - "MasVnrArea"
  - "BsmtFinSF1"
  - "BsmtFinSF2"
  - "BsmtUnfSF"
  - "TotalBsmtSF"
  - "1stFlrSF"
  - "2ndFlrSF"
  - "LowQualFinSF"
  - "GrLivArea"
  - "BsmtFullBath"
  - "BsmtHalfBath"
  - "FullBath"
  - "HalfBath"
  - "BedroomAbvGr"
  - "KitchenAbvGr"
  - "TotRmsAbvGrd"
  - "Fireplaces"
  - "GarageYrBlt"
  - "GarageCars"
  - "GarageArea"
  - "WoodDeckSF"
  - "OpenPorchSF"
  - "EnclosedPorch"
  - "3SsnPorch"
  - "ScreenPorch"
  - "PoolArea"
  - "MiscVal"
  - "MoSold"
  - "YrSold"

# API Configuration
api:
  title: "House Price Prediction API"
  description: "API for predicting house prices"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000